# Generated by Django 4.2.16 on 2025-02-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='phone_numbers', to='users.user'),
        ),
    ]
