# Generated by Django 4.2.16 on 2025-02-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_phonenumber_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='addresses', to='users.user')),
            ],
        ),
    ]
